### ISSUE TITLE
Can this code be used to compute geo_feature on 2D dataset?

### ISSUE THREAD

**Issue by SherlockCorleone** [drprojects/point_geometric_features#17]
I want to use the superpoint method on a 2D dataset. But ply_c.cpp in Supperpoint Graph and this code just support 3D dataset. how can I modify it to support 2D dataset.

**Comment by drprojects** [comment]
The present repo is designed for computing 3D point cloud handcrafted features, that we then feed to [cut-pursuit graph partition algorithm](https://gitlab.com/1a7r0ch3/parallel-cut-pursuit) to compute the superpoint partitions in [Superpoint Transformer](https://github.com/drprojects/superpoint_transformer). 

If you can formulate the problem you are working on as a graph partition, then you can also use [cut-pursuit](https://gitlab.com/1a7r0ch3/parallel-cut-pursuit). Up to you to define your graph connectivity and input node features. 

Due to the large amounts of requests we get, we can only provide support for the codebase we officially released, for the datasets we provided. We unfortunately cannot help with user-specific needs, and assume the users can figure this out themselves.
